# --------------------
# Spring Boot Basics
# --------------------
spring.application.name=TeaPost
server.port=8081

#mySql Config
spring.datasource.url=jdbc:mysql://localhost:3306/teapost
spring.datasource.username=root
spring.datasource.password=AnmolRS143@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.datasource.url=jdbc:mysql://userdb.c3c468ooe5dn.eu-north-1.rds.amazonaws.com:3306/admindb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#spring.datasource.username=appuser
#spring.datasource.password=AppPass123!
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Enable debug logging for Spring Security
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

jwt.private.key.path=classpath:private_key.pem
jwt.public.key.path=classpath:public_key.pem

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
